services:
  docs:
    image: plant_share_local_docs
    container_name: plant_share_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./plant_share:/app/plant_share:z
    ports:
      - '9000:9000'
    command: /start-docs
