# Generated by Django 5.0.9 on 2024-12-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_offer_user_offers_want_user_wants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name_plural': 'Commodities'},
        ),
    ]
